apiVersion: v1
kind: Service
metadata:
 name: private-service
 annotations:
   cloud.google.com/load-balancer-type: "Internal" # For GCP
   service.beta.kubernetes.io/aws-load-balancer-internal: "true" # For AWS
spec:
 selector:
   app: my-app
 ports:
   - port: 80
     targetPort: 8080
 type: LoadBalancer