apiVersion: v1
kind: Pod
metadata:
  name: my-python-pod
spec:
  containers:
    - name: my-python-container
      image: docker.io/eset0067/my-image:main
      ports:
        - containerPort: 5000
      imagePullPolicy: Always
  restartPolicy: OnFailure
